### ISSUE TITLE
Generated predictions.json file not representative of actual predictions file

### ISSUE THREAD

**Issue by amickan** [DIAGNijmegen/rse-grand-challenge-forge#14]
The generated example predictions.json file contains entries that are not in the actual predictions.json file: `is_json` and `is_image`. These should go. 

In turn, it is missing information that would be in an actual predictions.json file. It seems to me that the example file should be complete, right? I won't list all missing keys, but some examples are the pks of the interfaces, the api_url of the job, algorithm_image, started and completed at times of the jobs etc.

**Comment by chrisvanrun** [comment]
The `is_json` and `is_image` should go. That is a bug.

The other keys currently present per job (i.e. `['pk', 'inputs', 'outputs', 'status', 'started_at', 'completed_at']`) are a subset of the actual objects found in the predictions.json. The rationale is manyfold:
- need: no evaluation should involve itself with the api_url or the pk of the interfaces
- simplicity: it can be daunting to read the real predictions.json)
- limit the per submission of different fields in the example
