### ISSUE TITLE
Make `suggestions` to use `.gz` rather than `.xy`.

### ISSUE THREAD

**Issue by chrisvanrun** [DIAGNijmegen/rse-grand-challenge-forge#30]

**Comment by chrisvanrun** [comment]
We already do suggest using it:
https://github.com/DIAGNijmegen/demo-challenge-pack/blob/a12c4eb003d2bcb8bec36a60e5216f1aa2487ca5/test-phase/example-evaluation-method/evaluate.py#L14

**Comment by pkcakeout** [comment]
xy? I assume `xz` right? Also curious... why not xz? xz provides an about 33% better compression ratio than gzip, from our observations...

**Comment by jmsmkn** [comment]
Takes far longer to extract on our side.

**Comment by chrisvanrun** [comment]
> xy? I assume `xz` right? Also curious... why not xz? xz provides an about 33% better compression ratio than gzip, from our observations...

Correct, my ABC got the better of me.
