### ISSUE TITLE
Mysterious permissions errors when running test_run.sh twice

### ISSUE THREAD

**Issue by chrisvanrun** [DIAGNijmegen/rse-grand-challenge-forge#59]
During the workshop run, @koopmant ran into the problem that running the test script twice resulted in permission errors.

The test_run.sh has a secondary docker run, introduced to specifically target these permissions. Root user v.s. build created user. Hence, it is unclear why this occurred. It's being investigated.

**Comment by koopmant** [comment]
Tried again after a fresh reinstall of my system. I'm on Ubuntu 24.04.1 LTS. 
Steps I took:
- install docker desktop
- clone repo
- run the test script

Initial run works. Second run stops after:
> =+= Cleaning up any earlier output

Removed the -f argument from chmod. Now we see:
> chmod: changing permissions of '.../test/output': Operation not permitted

Tried adding my user to the docker group to run docker as non-root and see if that fixes it
`sudo usermod -aG docker $USER`

Did not fix it…

Also tried taking ownership using `chown`, but get the same permission issue.

**Comment by chrisvanrun** [comment]
Ok. So it fails on this part somewhere:

```Bash
if [ -d "$OUTPUT_DIR" ]; then
  # Ensure permissions are setup correctly
  # This allows for the Docker user to write to this location
  rm -rf "${OUTPUT_DIR}"/*
  chmod -f o+rwx "$OUTPUT_DIR"
else
  mkdir --mode=o+rwx "$OUTPUT_DIR"
fi
```

What are the permissions/ownership of the output directory right when you clone the repo, and what are they after the first run? `ls -alh` IIRC

**Comment by chrisvanrun** [comment]
Oh and while we are at it, what does `id -u` and `id -g` return at your command line?

**Comment by koopmant** [comment]
> Oh and while we are at it, what does `id -u` and `id -g` return at your command line?

both return 1000

**Comment by koopmant** [comment]
After clone I'm not sure, will check
after `mkdir` I'm the owner (obviously, but I checked regardless)
> drwxrwxrwx 2 thomas thomas 4096 Oct 18 14:37 output
after a successfull run, the owner is 100999:
> drwxrwxrwx 2 100999 100999 4.0K Oct 18 14:38 output

**Comment by chrisvanrun** [comment]
Thanks for testing. Huh, `100999` is odd! Given your id is `1000`, I would expect that this (at the end of the test_run.sh) fixes things:

```bash
docker run --rm \
    --quiet \
    --env HOST_UID=`id -u` \
    --env HOST_GID=`id -g` \
    --volume "$OUTPUT_DIR":/output \
    alpine:latest \
    /bin/sh -c 'chown -R ${HOST_UID}:${HOST_GID} /output'
```

**Comment by koopmant** [comment]
Well... When I remove that section, it actually works just fine? 
If I don´t run that section, the owner of the files in output/ is 100998 btw. But the owner of the output folder itself is still me.

**Comment by koopmant** [comment]
I think it has something to do with this; but I don't fully understand it yet
https://docs.docker.com/engine/security/userns-remap/

**Comment by chrisvanrun** [comment]
Current suspect: with `set -e` enabled, if a docker run has an error, the permission setter is not run. Should catch it in an exit so it always runs.

**Comment by koopmant** [comment]
disabling `set -e` does not change anything on my side. permission issue persists.

**Comment by chrisvanrun** [comment]
Was that all the output? Not sure if it worked from your comment. Sorry.

**Comment by koopmant** [comment]
Sorry, yes. That's all the output. It runs cleanup, then runs into the permission error again during chmod and then runs cleanup again on exit.

**Comment by chrisvanrun** [comment]
No problem! @amickan also ran into a similar looking problem. Hower above solution worked for her. Now I think it's possible that was from a different origin (the `set -e` origin). Yours likely stems from a slightly different ACL setup on Ubuntu 24.

Albeit if you temp fix it via sudo, forcing ownership to your own user, does it return running the test_run.sh twice?

I am hesitant to add calls like this, because it really kicks the interoperability of the script down a few nodges. 

```Bash

# Set the ACL recursively (-R) for the specified user and group
setfacl -R -m u:$USER:rwx -m g:$GROUP:rwx $DIRECTORY

# Set default ACL for future files and directories (so new files inherit the ACL)
setfacl -R -d -m u:$USER:rwx -m g:$GROUP:rwx $DIRECTORY

```

**Comment by koopmant** [comment]
> Albeit if you temp fix it via sudo, forcing ownership to your own user, does it return running the test_run.sh twice?

Sorry, I don't quite understand what you mean. 

FWIW, if you change this line:
`    /bin/sh -c 'chown -R ${HOST_UID}:${HOST_GID} /output'`
to 
`    /bin/sh -c 'chown -R ${HOST_UID}:${HOST_GID} /output/*'` 
the issue of running the script again is fixed. On my system, the ownership is then still on another user id, so I cannot open the file without providing root authentication; but this should still work on other systems. 

the line
`chmod o+rwx "$OUTPUT_DIR"`
is then unneccessary, because the directory then never changed ownership. (But it doesn´t raise an issue.)

**Comment by koopmant** [comment]
> Sorry, let me clarify: if you fix ownership once. Does the proposed test_run.sh then keep working, even if ran multiple times?

Yes, that sort of works. The chown attempted in the last docker command then fails with a permission error. So I remain the owner of the directory and the rest of the script is successfull. Still, that means the current user does not become owner of the files in the output directory. But at least the script runs and creates output.

**Comment by chrisvanrun** [comment]
@koopmant , let's discuss this during out meet-meeting. =)

**Comment by chrisvanrun** [comment]
Hint for fix, there seems to be a new mapping in some Linux distros (or new Docker Engine, dunno) that maps internal docker uids to system ones.

```
docker run --rm --env HOST_UID=1000 --env HOST_GID=1000 --volume /home/thomas/code/rse-workshop-2024/evaluation-methods/test/output:/output --entrypoint /bin/sh example-evaluation -c "chmod o+rwX /output/*"
```

**Comment by chrisvanrun** [comment]
See fix in: https://github.com/DIAGNijmegen/rse-workshop-2024/commit/5cae84425f1824bd4c92fbddbf660f859ef28228

Should be replicated to forge.
